### ISSUE TITLE
Use ReifiedType for .runtimeType

### ISSUE THREAD

**Issue by karlklose** [dart-lang/reify#6]
.runtimeType should return a core.Type instance based on the ReifiedType of the object.

Two possible options:
- Let ReifiedType implement core.Type. This would require us to make all methods on ReifiedType subclasses private since these objects leak into the normal program. We also have to take care for the runtimeType of a ReifiedType.
- Wrap the ReifiedType and forward toString, hashCode and operator==.

**Comment by peter-ahe-google** [comment]
I tend to worry about the overhead of the wrapper objects. My preference would be to make ReifiedType implement Type and have top-level methods that allow access to the private methods.

For example:

```dart
class ReifiedType implements Type {
  bool _isSubtype(ReifiedType other) { ... }
}

bool isSubtype(ReifiedType s, ReifiedType t) => s._isSubtype(t);
```
